import type { NextPage } from 'next';
import Head from 'next/head';

import SignUpForm from '../../app/components/SignUp';

const SignUp: NextPage = () => {
  return (
    <>
      <Head>
        <title>SignUp Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SignUpForm />
    </>
  );
};

export default SignUp;
