import type { NextPage } from 'next';
import Head from 'next/head';

import SignInForm from '../../app/components/SignIn';

const SignIn: NextPage = () => {
  return (
    <>
      <Head>
        <title>SignIn Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SignInForm />
    </>
  );
};

export default SignIn;
