import Head from 'next/head';
import type { NextPage } from 'next';
import { Button, Stack, Typography } from '@mui/material';
import Link from 'next/link';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Typography align="center" variant="h2" component="div" gutterBottom>
        It is Home Page
      </Typography>
      <Stack direction="row" justifyContent="center" spacing={2}>
        <Link href="/auth/signup" passHref>
          <Button variant="outlined">Регистрация</Button>
        </Link>
        <Link href="/auth/signin" passHref>
          <Button variant="outlined">Войти</Button>
        </Link>
      </Stack>
    </>
  );
};

export default Home;
