import { useEffect } from 'react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import type { NextPage } from 'next';

import ProfilePage from '../app/components/ProfilePage';
import { useAuth } from '../app/hooks/useAuth';

const Profile: NextPage = () => {
  const router = useRouter();
  const userInfo = useAuth();

  if (!userInfo.isAuth) {
    router.push('/');
    return null;
  }

  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ProfilePage {...userInfo} />
    </>
  );
};

export default Profile;
